name: Fetch Release Statistics

on:
  push:
  workflow_dispatch: # Manually triggered
  schedule:
    - cron: '0 0 * * *' # on every midnight

permissions:
  actions: write

jobs:
  update-release-statistics:
    runs-on: ubuntu-latest
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Add Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade plotly pandas

    - name: Extract Stats
      run: |
        python fetch.py

    - name: Generate Plot
      run: |
        python visualize.py

    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Update statistics'
        add: '*.json index.html --force'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: html
