name: Fetch Release Statistics

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # on every midnight

permissions:
  actions: write

jobs:
  update-release-statistics:
    runs-on: ubuntu-latest
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'        
        
    - name: Extract Stats
      run: |
        python main.py
        ls -lh
        
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Update statistics'
        add: '*.json --force'
        
        
        
        
