name: Fetch Release Statistics

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  update-release-statistics:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
        
    - name: Update Stats
      run: |
        python main.py
